### PR TITLE
fix alt key escape in combination

### LINKED ISSUE #181: Some keybindings do not work well in tmux
For example:
Alt+{Up,Down,Up,Down} results in:

```
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
~/go/src/github.com/elves/elvish> [A[B[A[B                                                                                                huiyiqun@edge
```

And Ctrl+{Left,Right} is parsed as {Left,Right}

### PR DESCRIPTION
**Pull request by tw4452852**
fix #181

Signed-off-by: Tw <tw19881113@gmail.com>

### CODE REVIEW

File: edit/tty/reader.go [hunk 1]
```diff
@@ -148,7 +148,14 @@ func (rd *Reader) readOne(r rune) {
 
 	switch r {
 	case 0x1b: // ^[ Escape
+		var prefixMod ui.Mod
 		r2 := readRune()
+		// some terminals may also send Alt character which is same as ESC
```
Comment (xiaq) [inline edit/tty/reader.go]: Elvish already handles the use of Alt-sends-Escape in some cases (near the end of this function, search "Something other than"), and this branch is specifically for handling double ESCs. I would rather you clarify this comment to make it read like:

> According to https://unix.stackexchange.com/a/73697, rxvt and derivatives prepend another ESC to a CSI-style or G3-style sequence to signal Alt. If that happens, remember this now; it will be later picked up when parsing those two kinds of sequences.

Also, I'd rather you make this a boolean flag `hasTwoLeadingESC`; a Mod seems needlessly general.

File: edit/tty/reader.go [hunk 2]
```diff
@@ -196,7 +203,7 @@ func (rd *Reader) readOne(r rune) {
 				}
 				mod := mouseModify(int(cb))
 				unit = MouseEvent{
-					Pos{int(cy) - 32, int(cx) - 32}, down, button, mod}
+					Pos{int(cy) - 32, int(cx) - 32}, down, button, mod | prefixMod}
```
Comment (xiaq) [inline edit/tty/reader.go]: Mouse events have very different escape sequences. Do you have evidence that double ESC can arise in this case? If not, I'd rather you remove this.

File: edit/tty/reader.go [hunk 3]
```diff
@@ -239,7 +246,7 @@ func (rd *Reader) readOne(r rune) {
 				down := r == 'M'
 				button := nums[0] & 3
 				mod := mouseModify(nums[0])
-				unit = MouseEvent{Pos{nums[2], nums[1]}, down, button, mod}
+				unit = MouseEvent{Pos{nums[2], nums[1]}, down, button, mod | prefixMod}
```
Comment (xiaq) [inline edit/tty/reader.go]: Ditto.

File: edit/tty/reader.go (hunk 2 above)
Comment (tw4452852) [reply edit/tty/reader.go]: Ok, i have just removed this.

File: edit/tty/reader.go (hunk 1 above)
Comment (tw4452852) [reply edit/tty/reader.go]: Done.

File: edit/tty/reader.go (hunk 3 above)
Comment (tw4452852) [reply edit/tty/reader.go]: Ditto.
